//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public ClassRoom()
        {
            this.FeeSettings = new HashSet<FeeSetting>();
            this.StudentClassRooms = new HashSet<StudentClassRoom>();
            this.SubjectTeacherClassRooms = new HashSet<SubjectTeacherClassRoom>();
        }
    
        public string ClassRoomName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual ICollection<FeeSetting> FeeSettings { get; set; }
        public virtual ICollection<StudentClassRoom> StudentClassRooms { get; set; }
        public virtual ICollection<SubjectTeacherClassRoom> SubjectTeacherClassRooms { get; set; }
    }
}
