//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupName
    {
        public GroupName()
        {
            this.GroupMembers = new HashSet<GroupMember>();
            this.GroupWorkResults = new HashSet<GroupWorkResult>();
            this.GroupWorkSchedules = new HashSet<GroupWorkSchedule>();
        }
    
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public string GroupName1 { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual SubjectTeacherClassRoom SubjectTeacherClassRoom { get; set; }
        public virtual ICollection<GroupWorkResult> GroupWorkResults { get; set; }
        public virtual ICollection<GroupWorkSchedule> GroupWorkSchedules { get; set; }
    }
}
