//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualWorkSchedule
    {
        public IndividualWorkSchedule()
        {
            this.IndividualWorkResults = new HashSet<IndividualWorkResult>();
        }
    
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public string IndividualWorkName { get; set; }
        public System.DateTime IndividualWorkGivenDate { get; set; }
        public System.DateTime IndividualWorkSubmissionDate { get; set; }
        public int OutOf { get; set; }
        public string IndividualWorkInformation { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual ICollection<IndividualWorkResult> IndividualWorkResults { get; set; }
        public virtual SubjectTeacherClassRoom SubjectTeacherClassRoom { get; set; }
    }
}
