//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonClass
    {
        public LessonClass()
        {
            this.QuizSchedules = new HashSet<QuizSchedule>();
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.TestSchedules = new HashSet<TestSchedule>();
        }
    
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public System.Guid DayGuid { get; set; }
        public System.Guid PeriodGuid { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Period Period { get; set; }
        public virtual SubjectTeacherClassRoom SubjectTeacherClassRoom { get; set; }
        public virtual ICollection<QuizSchedule> QuizSchedules { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        public virtual ICollection<TestSchedule> TestSchedules { get; set; }
    }
}
