//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.ParentComments = new HashSet<ParentComment>();
        }
    
        public string Fullname { get; set; }
        public string Address { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string ReservedPhoneNumber { get; set; }
        public System.Guid StudentGuid { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual ICollection<ParentComment> ParentComments { get; set; }
        public virtual Student Student { get; set; }
    }
}
