//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSchedule
    {
        public QuizSchedule()
        {
            this.QuizResults = new HashSet<QuizResult>();
        }
    
        public System.Guid LessonClassGuid { get; set; }
        public string QuizName { get; set; }
        public string QuizInformation { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int OutOf { get; set; }
        public System.DateTime GivenDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual LessonClass LessonClass { get; set; }
        public virtual ICollection<QuizResult> QuizResults { get; set; }
    }
}
