//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.SubjectTeacherClassRooms = new HashSet<SubjectTeacherClassRoom>();
            this.TotalGroupWorkResults = new HashSet<TotalGroupWorkResult>();
            this.TotalIndividualWorkResults = new HashSet<TotalIndividualWorkResult>();
            this.TotalQuizResults = new HashSet<TotalQuizResult>();
            this.TotalSums = new HashSet<TotalSum>();
            this.TotalTestResults = new HashSet<TotalTestResult>();
        }
    
        public string SubjectName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual ICollection<SubjectTeacherClassRoom> SubjectTeacherClassRooms { get; set; }
        public virtual ICollection<TotalGroupWorkResult> TotalGroupWorkResults { get; set; }
        public virtual ICollection<TotalIndividualWorkResult> TotalIndividualWorkResults { get; set; }
        public virtual ICollection<TotalQuizResult> TotalQuizResults { get; set; }
        public virtual ICollection<TotalSum> TotalSums { get; set; }
        public virtual ICollection<TotalTestResult> TotalTestResults { get; set; }
    }
}
