//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTeacherClassRoom
    {
        public SubjectTeacherClassRoom()
        {
            this.ExamSchedules = new HashSet<ExamSchedule>();
            this.ExerciseBookResults = new HashSet<ExerciseBookResult>();
            this.GroupNames = new HashSet<GroupName>();
            this.GroupWorkSchedules = new HashSet<GroupWorkSchedule>();
            this.IndividualWorkSchedules = new HashSet<IndividualWorkSchedule>();
            this.LessonClasses = new HashSet<LessonClass>();
        }
    
        public System.Guid ClassRoomGuid { get; set; }
        public System.Guid SubjectGuid { get; set; }
        public System.Guid TeacherGuid { get; set; }
        public Nullable<bool> HomeClassRoom { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual ICollection<ExamSchedule> ExamSchedules { get; set; }
        public virtual ICollection<ExerciseBookResult> ExerciseBookResults { get; set; }
        public virtual ICollection<GroupName> GroupNames { get; set; }
        public virtual ICollection<GroupWorkSchedule> GroupWorkSchedules { get; set; }
        public virtual ICollection<IndividualWorkSchedule> IndividualWorkSchedules { get; set; }
        public virtual ICollection<LessonClass> LessonClasses { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
