//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.SubjectTeacherClassRooms = new HashSet<SubjectTeacherClassRoom>();
            this.TeacherComments = new HashSet<TeacherComment>();
        }
    
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string GrandFatherName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.Guid GenderGuid { get; set; }
        public string Address { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string ReservedPhoneNumber { get; set; }
        public string Experience { get; set; }
        public System.DateTime EngagementDate { get; set; }
        public decimal Salary { get; set; }
        public System.Guid LogInUserId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<SubjectTeacherClassRoom> SubjectTeacherClassRooms { get; set; }
        public virtual ICollection<TeacherComment> TeacherComments { get; set; }
    }
}
