//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalSum
    {
        public System.Guid AcademicCalanderGuid { get; set; }
        public System.Guid StudentGuid { get; set; }
        public System.Guid SubjectGuid { get; set; }
        public Nullable<System.Guid> TotalIndividualWorkResultGuid { get; set; }
        public Nullable<System.Guid> TotalGroupWorkResultGuid { get; set; }
        public Nullable<System.Guid> TotalQuizResultGuid { get; set; }
        public Nullable<System.Guid> TotalTestResultGuid { get; set; }
        public Nullable<System.Guid> ExerciseBookResultGuid { get; set; }
        public Nullable<System.Guid> ExamResultGuid { get; set; }
        public decimal Sum { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> EventSource { get; set; }
        public string ComputerName { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual AcademicCalander AcademicCalander { get; set; }
        public virtual ExamResult ExamResult { get; set; }
        public virtual ExerciseBookResult ExerciseBookResult { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual TotalGroupWorkResult TotalGroupWorkResult { get; set; }
        public virtual TotalIndividualWorkResult TotalIndividualWorkResult { get; set; }
        public virtual TotalQuizResult TotalQuizResult { get; set; }
        public virtual TotalTestResult TotalTestResult { get; set; }
    }
}
