//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInLocation
    {
        public Nullable<System.Guid> UserGuid { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string ComputerName { get; set; }
        public Nullable<int> EventSource { get; set; }
        public System.Guid TableRowGuid { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
