//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FeeSettingList
    {
        public string ClassRoomName { get; set; }
        public string MonthName { get; set; }
        public decimal Amount { get; set; }
        public System.Guid FeeSettingGuid { get; set; }
        public System.Guid ClassRoomGuid { get; set; }
        public System.Guid MonthGuid { get; set; }
    }
}
