//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GroupWorkScheduleList
    {
        public string GroupWork { get; set; }
        public System.DateTime GroupWorkGivenDate { get; set; }
        public System.DateTime GroupWorkSubmissionDate { get; set; }
        public int OutOf { get; set; }
        public string Title { get; set; }
        public string Information { get; set; }
        public System.Guid GroupWorkScheduleGuid { get; set; }
        public System.Guid GroupNameGuid { get; set; }
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public System.Guid TeacherGuid { get; set; }
        public System.Guid SubjectGuid { get; set; }
        public System.Guid ClassRoomGuid { get; set; }
    }
}
