//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GroupWorkResultList
    {
        public string GroupName { get; set; }
        public decimal Result { get; set; }
        public int OutOf { get; set; }
        public string SubjectClassRoom { get; set; }
        public string Comment { get; set; }
        public System.Guid GroupWorkResultGuid { get; set; }
    }
}
