//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaymentCalanderList
    {
        public string MonthName { get; set; }
        public System.DateTime RegularPaymentDateFrom { get; set; }
        public System.DateTime RegularPaymentDateTo { get; set; }
        public System.Guid PaymentCalanderGuid { get; set; }
        public System.Guid MonthGuid { get; set; }
    }
}
