//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaymentList
    {
        public string Payment { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int TinNumber { get; set; }
        public int FSNumber { get; set; }
    }
}
