//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentAttendanceList
    {
        public string StudentAttendance { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid TableRowGuid { get; set; }
        public string Comment { get; set; }
    }
}
