//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentsForTestScheduleDataView
    {
        public string TestSchdule { get; set; }
        public int OutOf { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime GivenDate { get; set; }
        public string StudentName { get; set; }
        public string ClassRoomName { get; set; }
        public System.Guid TestScheduleGuid { get; set; }
        public System.Guid StudentGuid { get; set; }
        public System.Guid ClassRoomGuid { get; set; }
        public System.Guid TeacherGuid { get; set; }
        public System.Guid SubjectGuid { get; set; }
        public System.Guid DayGuid { get; set; }
        public System.Guid PeriodGuid { get; set; }
        public System.Guid SessionGuid { get; set; }
        public Nullable<System.Guid> SubjectTeacherClassRoomGuid { get; set; }
        public System.Guid StudentClassRoomGuid { get; set; }
        public Nullable<System.Guid> LessonClassGuid { get; set; }
    }
}
