//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentsForIndividualWorkScheduleDataView
    {
        public string IndividualWorkSchedule { get; set; }
        public int OutOf { get; set; }
        public System.DateTime IndividualWorkGivenDate { get; set; }
        public System.DateTime IndividualWorkSubmissionDate { get; set; }
        public string StudentFullName { get; set; }
        public string ClassRoomName { get; set; }
        public System.Guid StudentGuid { get; set; }
        public System.Guid IndividualWorkScheduleGuid { get; set; }
        public Nullable<System.Guid> ClassRoomGuid { get; set; }
        public Nullable<System.Guid> TeacherGuid { get; set; }
        public Nullable<System.Guid> SubjectGuid { get; set; }
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public System.Guid StudentClassroomGuid { get; set; }
    }
}
