//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentList
    {
        public string StudentFullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string GenderName { get; set; }
        public System.Guid StudentGuid { get; set; }
        public System.Guid GenderGuid { get; set; }
    }
}
