//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentsForLessonClassDataView
    {
        public string lessonclass { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public string StudentName { get; set; }
        public string TeacherName { get; set; }
        public string ClassRoomName { get; set; }
        public System.Guid studentGuid { get; set; }
        public System.Guid LogInUserId { get; set; }
        public Nullable<System.Guid> ClassRoomGuid { get; set; }
        public System.Guid teacherGuid { get; set; }
        public System.Guid subjectGuid { get; set; }
        public System.Guid dayGuid { get; set; }
        public System.Guid periodGuid { get; set; }
        public System.Guid sessionGuid { get; set; }
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public Nullable<System.Guid> studentclassroomGuid { get; set; }
        public System.Guid lessonclassGuid { get; set; }
    }
}
