//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentsForExamScheduleDataView
    {
        public string examSchdule { get; set; }
        public string day { get; set; }
        public int OutOf { get; set; }
        public string ExamInformation { get; set; }
        public string StudentName { get; set; }
        public string ClassRoomName { get; set; }
        public System.Guid ExamScheduleGuid { get; set; }
        public System.Guid StudentGuid { get; set; }
        public Nullable<System.Guid> ClassRoomGuid { get; set; }
        public System.Guid TeacherGuid { get; set; }
        public System.Guid SubjectGuid { get; set; }
        public System.Guid DayGuid { get; set; }
        public System.Guid SessionGuid { get; set; }
        public System.Guid SubjectTeacherClassRoomGuid { get; set; }
        public System.Guid StudentClassRoomGuid { get; set; }
    }
}
