//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentInfromationDataView
    {
        public string Information { get; set; }
        public string GenderName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string RoleName { get; set; }
        public System.Guid studentGuid { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public System.Guid ClassRoomGuid { get; set; }
        public System.Guid studentclassroomGuid { get; set; }
    }
}
