//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentUnPaymentDataView
    {
        public string StudentName { get; set; }
        public string ClassRoomName { get; set; }
        public string PaymentName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartTermDate { get; set; }
        public Nullable<System.DateTime> EndTermDate { get; set; }
        public Nullable<System.DateTime> RegularPaymentDateFrom { get; set; }
        public Nullable<System.DateTime> RegularPaymentDateTo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> TinNumber { get; set; }
        public Nullable<int> FSNumber { get; set; }
        public Nullable<System.Guid> studentGuidOnStudents { get; set; }
        public Nullable<System.Guid> studentGuidOnPayments { get; set; }
        public Nullable<System.Guid> paymentGuid { get; set; }
        public Nullable<System.Guid> feesettingGuid { get; set; }
        public Nullable<System.Guid> classroomGuid { get; set; }
        public Nullable<System.Guid> paymentcalanderGuid { get; set; }
    }
}
