//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TeacherList
    {
        public string TeacherFullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string GenderName { get; set; }
        public string Address { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string ReservedPhoneNumber { get; set; }
        public string Experience { get; set; }
        public System.DateTime EngagementDate { get; set; }
        public decimal Salary { get; set; }
        public System.Guid TeacherGuid { get; set; }
        public System.Guid GenderGuid { get; set; }
        public System.Guid LogInUserId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    }
}
